// Auto-generated by build.rs
mod limits;
mod gitlogs;
mod server_backups;
mod root;
mod core;
mod server_member_backups;

/// List of modules available. Not all may be enabled
pub fn modules() -> Vec<crate::silverpelt::Module> {
    vec![
        limits::module(),
        gitlogs::module(),
        server_backups::module(),
        root::module(),
        core::module(),
        server_member_backups::module(),
    ]
}