[package]
name = "bot_modules_server_member_backups"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Anti-Raid specific
silverpelt = { path = "../rust.silverpelt" }
