[workspace]
members = [
    "services/bot/crates/*",
    "services/bot", 
    "services/template-worker",
    "core/rust/rust.*"
]
exclude = [
    "infra/templating-types",
    "infra/templating-types/darklua", # Avoid workspace conflicts
    "infra/templating-template/darklua"
]
resolver = "2"


[profile.release]
strip = true  # Automatically strip symbols from the binary.
incremental = true # Enable incremental compilation.
opt-level = 3
