services:
  # Redis
  api_redis:
    container_name: api_redis
    networks:
      - antiraid_api # Only communicates with API
    image: redis:7.2.7 # Use 7.2.7 to avoid licensing change with 7.4+
    expose:
      - 6379
    command: redis-server --save 900 1 --save 300 10 --save 60 10000 --loglevel notice --bind 0.0.0.0
    volumes:
      - ./data/state/redis:/data

  # Nirn Proxy
  nirn_proxy:
    container_name: nirn_proxy
    networks:
      - antiraid_infra
      - antiraid_internal # Exposed to internal services
    depends_on:
      sandwich:
        condition: service_healthy
    build:
      context: ./infra/nirn-proxy
      dockerfile: ./Dockerfile
    volumes:
      - ./infra/nirn-proxy/secrets.json:/secrets.json:ro
    command: cache-endpoints=false port=3221 ratelimit-over-408 endpoint-rewrite=/api/gateway/bot@http://sandwich:29334/antiraid,/api/v*/gateway/bot@http://sandwich:29334/antiraid token-map-file=secrets.json
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3221/nirn/healthz" ]
      interval: 3s
      timeout: 10s
      retries: 3
    ports:
      - "3222:3221" # And exposed to host for testing/auditing

  # Sandwich
  sandwich:
    container_name: sandwich
    networks:
      - antiraid_infra
      - antiraid_internal # Exposed to internal services
    build:
      context: ./infra/Sandwich-Daemon
      dockerfile: ./Dockerfile
    volumes:
      - ./infra/Sandwich-Daemon/sandwich.yaml:/sandwich.yaml:ro
    command: ./app/sandwich -configurationPath=/sandwich.yaml -prometheusAddress :3931 -httpEnabled --httpHost 0.0.0.0:29334 -level debug
    environment:
      EXTERNAL_GATEWAY_ADDRESS: ws://sandwich:3600
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:29334/antiraid/api/v9/gateway/bot" ]
      interval: 10s
      timeout: 10s
      retries: 1000000000
    ports:
      - "29334:29334" # Exposed to host for testing/auditing
      - "3931:3931" # Prometheus metrics
      - "3600:3600" # Websocket connection for the bot

  postgres:
    container_name: postgres
    networks:
      - antiraid_internal # Exposed to internal services
    build:
      context: ./data/docker/postgres
      dockerfile: ./Dockerfile
    # Expose /seed.iblcli-seed
    volumes:
      - ./data/seed.iblcli-seed:/seed.iblcli-seed:ro
      - ./data/state/postgres-other:/var/lib/postgresql
      - ./data/state/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "antiraid" ]
      interval: 3s
      timeout: 10s
      retries: 3

  # Bot process itself
  bot:
    container_name: bot
    networks:
      - antiraid_internal # Exposed to internal services
    depends_on:
      nirn_proxy:
        condition: service_healthy
      sandwich:
        condition: service_healthy
      postgres:
        condition: service_healthy
    build:
      context: ./services/bot
      dockerfile: ./Dockerfile
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    environment:
      POSTGRES_URL: postgres://antiraid:AnTiRaId123!@postgres:5432/antiraid
      PROXY_URL: http://nirn_proxy:3221
      TEMPLATE_WORKER_URL: template-worker
      SANDWICH_URL: http://sandwich:29334
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:20000/state" ]
      interval: 3s
      timeout: 10s
      retries: 10

  # Template worker process
  template-worker:
    container_name: template-worker
    networks:
      - antiraid_internal # Exposed to internal services
    depends_on:
      nirn_proxy:
        condition: service_healthy
      sandwich:
        condition: service_healthy
      postgres:
        condition: service_healthy
      bot:
        condition: service_started
    build:
      context: ./services/template-worker
      dockerfile: ./Dockerfile
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    environment:
      POSTGRES_URL: postgres://antiraid:AnTiRaId123!@postgres:5432/antiraid
      PROXY_URL: http://nirn_proxy:3221
      TEMPLATE_WORKER_URL: template_worker
      SANDWICH_URL: http://sandwich:29334
      RUST_LOG: "template-worker=info"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:60000" ]
      interval: 3s
      timeout: 10s
      retries: 100

  api:
    container_name: api
    networks:
      - antiraid_internal # Doesn't need external net access
      - antiraid_api
    depends_on:
      api_redis:
        condition: service_started
      nirn_proxy:
        condition: service_started
      postgres:
        condition: service_healthy
      bot:
        condition: service_healthy
    build:
      context: ./services/api
      dockerfile: ./Dockerfile
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    environment:
      REDIS_URL: redis://api_redis:6379/1
      PROXY_URL: http://nirn_proxy:3221
      BOT_URL: http://bot

  # Nginx process to expose the API outwards while ensuring API itself doesn't get any
  # external net access
  api_exposer:
    container_name: api_exposer
    networks:
      - antiraid_api
      - antiraid_infra # Needs access to the outside world
    depends_on:
      api:
        condition: service_started
    image: nginx:1.27.4-alpine
    volumes:
      - ./data/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "5600:5600" # Expose API to host for testing/auditing
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081" ]
      interval: 3s
      timeout: 10s
      retries: 3

networks:
  antiraid_infra:
    name: antiraid_infra
    driver: bridge
    internal: false # Infra needs external access
  antiraid_internal:
    name: antiraid_internal
    driver: bridge
    internal: true # No external net access
  antiraid_api:
    # Used for internal API services (Redis/Nginx etc.)
    name: antiraid_api
    driver: bridge
    internal: true # No external net access
