// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PlatformUser { id: string, username: string, avatar: string, display_name: string, bot: boolean, status: string, }