[package]
name = "rust_rpc_server_bot"
version = "6.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = { git = "https://github.com/serenity-rs/poise", branch = "serenity-next" }
serde = "1.0"
log = "0.4"
env_logger = "0.11"
sqlx = { version = "0.8", features = [ "runtime-tokio-rustls", "postgres", "chrono", "uuid", "json"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "rustls-tls-native-roots"] }
serde_json = "1.0"
futures-util = "0.3"
indexmap = { version = "2", features = ["serde"] }
dashmap = { version = "5", features = ["serde", "inline", "rayon"] }
fred = { version = "9.0.3", features = ["serde-json", "subscriber-client"] }
bitflags = "2"
async-trait = "0.1.80"
axum = { version = "0.7.5", features = ["macros"] }

# Anti-Raid specific
splashcore_rs = { path = "../../core/rust.std" }
gwevent = { path = "../../core/rust.gwevent" }
module_settings = { path = "../../core/rust.module_settings" }
proxy_support = { path = "../../core/rust.proxy_support" }
config = { path = "../../core/rust.config" }
cap = { version = "0.1.2", features = ["stats"] }
silverpelt = { path = "../../core/rust.silverpelt" }
permissions = { path = "../../core/rust.permissions" }
bot_modules_default = { path = "../../core/rust.bot_modules_default" }
bot_binutils = { path = "../../core/rust.binutils" }
rust_rpc_server = { path = "../../core/rust.rpc_server" }

[dependencies.tokio]
version = "1"
features = ["sync", "macros", "rt-multi-thread"]

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "next"
features = ["model", "http", "cache", "rustls_backend", "unstable"]

[dependencies.kittycat]
git = "https://github.com/infinitybotlist/kittycat"
branch = "main"

[dependencies.botox]
git = "https://github.com/infinitybotlist/botox"
branch = "main"
