[package]
name = "simplegwproxy2"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
panic = "abort"  # Abort on panic. This is what we want for a bot.

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0", features = ["rc"] }
log = "0.4"
env_logger = "0.9"
chrono = { version = "0.4", features = ["serde"]}
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls", "rustls-tls-native-roots"] }
serde_json = "1.0"
serde_yaml = "0.9"
serde_repr = "0.1"
once_cell = "1.17"
futures-util = "0.3"
indexmap = { version = "2.1", features = ["serde"] }
dashmap = { version = "5", features = ["serde", "inline", "rayon"] }
strum = "0.24"
strum_macros = "0.24"
splashcore_rs = { path = "../splashcore_rs" }
tower-http = { version = "0.3", features = ["cors"] }
num-traits = "0.2.14"
moka = { version = "0.12.3", features = ["future", "futures-util"] }
tokio-websockets = { version = "0.5.1", features = ["rustls-native-roots", "ring", "http-integration", "rand", "server", "simd"] }
small-fixed-array = "*"
url = "*"

[dependencies.tokio]
version = "1"
default-features = true
features = ["full"]

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "next"
features = ["model", "http", "cache", "rustls_backend"]
