[package]
name = "templating"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
base_data = { path = "../rust.base_data" }
once_cell = "1"
moka = { version = "0.12", features = ["future", "futures-util", "sync"] }
dashmap = { version = "5", features = ["serde", "inline", "rayon"] }
indexmap = { version = "2", features = ["serde"] }

# Anti-Raid specific
splashcore_rs = { path = "../rust.std" }
rhai = { version = "1.19.0", features = ["std", "serde", "no_closure", "sync"] }

[dependencies.tokio]
version = "1"
default-features = true
features = ["full", "macros", "rt-multi-thread"]

[dependencies.tera]
git = "https://github.com/anti-raid/tera"
branch = "master"
features = ["preserve_order", "builtins", "async"]

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "next"
features = ["model", "http", "cache", "rustls_backend", "unstable"]

[dependencies.kittycat]
git = "https://github.com/infinitybotlist/kittycat"
branch = "main"

