[package]
name = "templating"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
moka = { version = "0.12", features = ["future", "futures-util", "sync"] }
indexmap = { version = "2", features = ["serde"] }
futures-util = "0.3"
log = "0.4"
sqlx = { version = "0.8", features = [ "runtime-tokio-rustls", "postgres", "chrono", "uuid", "json"] } 
rand = "0.8"
typetag = "0.2"
chrono = { version = "0.4", features = ["serde"]}
scc = "2"

# @lune/datetime
chrono_lc = "0.1"
thiserror = "1.0"
self_cell = "1"

# @lune/regex
regex = "1"

# @lune/serde
async-compression = { version = "0.4", features = [
    "tokio",
    "brotli",
    "deflate",
    "gzip",
    "zlib",
] }
bstr = "1.9"
lz4 = "1.26"
serde_yaml = "0.9"
toml = { version = "0.8", features = ["preserve_order"] }
digest = "0.10.7"
hmac = "0.12.1"
md-5 = "0.10.6"
sha1 = "0.10.6"
sha2 = "0.10.8"
sha3 = "0.10.8"
# This feature MIGHT break due to the unstable nature of the digest crate.
# Check before updating it.
blake3 = { version = "=1.5.0", features = ["traits-preview"] }

# Anti-Raid specific
permissions = { path = "../rust.permissions" }
gwevent = { path = "../rust.gwevent" }
config = { path = "../rust.config" }
limits = { path = "../rust.limits" }

# Template language support
mlua = { version = "0.10.0-rc.1", features = ["async", "luau", "serialize", "macros", "send"], optional = true } # Supported by default

[dependencies.tokio]
version = "1"
features = ["sync", "macros", "rt-multi-thread"]

[dependencies.serenity]
git = "https://github.com/Anti-Raid/serenity"
branch = "next"
features = ["model", "http", "cache", "rustls_backend", "unstable"]

[dependencies.kittycat]
git = "https://github.com/infinitybotlist/kittycat"
branch = "main"

[dependencies.botox]
git = "https://github.com/Anti-Raid/botox"
branch = "main"

[features]
default = ["lua"]
lua = ["dep:mlua"] # Supported by default
ext-test = []