[package]
name = "templating"
version = "0.1.0"
edition = "2021"

[dependencies]
base_data = { path = "../rust.base_data" }
once_cell = "1"
moka = { version = "0.12", features = ["future", "futures-util"] }
dashmap = { version = "5", features = ["serde", "inline", "rayon"] }
indexmap = { version = "2", features = ["serde"] }

[dependencies.tokio]
version = "1"
default-features = true
features = ["full", "macros", "rt-multi-thread"]

[dependencies.tera]
git = "https://github.com/anti-raid/tera"
branch = "master"
features = ["preserve_order", "builtins", "async"]

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "next"
features = ["model", "http", "cache", "rustls_backend", "unstable"]
