[package]
name = "templating"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
moka = { version = "0.12", features = ["future", "futures-util", "sync"] }
indexmap = { version = "2", features = ["serde"] }
futures-util = "0.3"
log = "0.4"
sqlx = { version = "0.8", features = [ "runtime-tokio-rustls", "postgres", "chrono", "uuid", "json"] } 
rand = "0.8"
typetag = "0.2"

# Anti-Raid specific
permissions = { path = "../rust.permissions" }
gwevent = { path = "../rust.gwevent" }
config = { path = "../rust.config" }
limits = { path = "../rust.limits" }

# Template language support
mlua = { version = "0.10.0-rc.1", features = ["async", "luau", "serialize", "macros", "send"], optional = true } # Supported by default

[dependencies.tokio]
version = "1"
features = ["sync", "macros", "rt-multi-thread"]

[dependencies.serenity]
git = "https://github.com/Anti-Raid/serenity"
branch = "next"
features = ["model", "http", "cache", "rustls_backend", "unstable"]

[dependencies.kittycat]
git = "https://github.com/infinitybotlist/kittycat"
branch = "main"

[features]
default = ["lua"]
lua = ["dep:mlua"] # Supported by default
ext-test = []