[package]
name = "module_settings"
version = "6.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
sqlx = { version = "0.8", features = [ "runtime-tokio-rustls", "postgres", "chrono", "uuid", "json"] }
chrono = { version = "0.4", features = ["serde"]}
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "rustls-tls-native-roots"] }
serde_json = "1.0"
futures-util = "0.3"
indexmap = { version = "2", features = ["serde"] }
moka = { version = "0.12", features = ["future", "futures-util"] }

# Anti-Raid specific
splashcore_rs = { path = "../rust.std" }
templating = { path = "../rust.templating" }
proxy_support = { path = "../rust.proxy_support" }
async-recursion = "1.1.1"
async-trait = "0.1"

[dependencies.serenity]
git = "https://github.com/Anti-Raid/serenity"
branch = "next"
features = ["model", "http", "cache", "rustls_backend", "unstable"]

[dependencies.botox]
git = "https://github.com/Anti-Raid/botox"
branch = "main"
