# syntax=docker/dockerfile:1

FROM postgres:17.4-bookworm

# Set environment variables
ENV POSTGRES_USER=seaweed
ENV POSTGRES_PASSWORD=seaweed11!
ENV POSTGRES_DB=seaweed
ENV POSTGRES_PORT=5432
ENV POSTGRES_INITDB_ARGS="--encoding=UTF8 --locale=C --lc-collate=C --lc-ctype=C"