[package]
name = "rust_rpc_server"
version = "6.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
axum = "0.7.5"
hyper = "1"
hyper-util = { version = "0.1", features = ["tokio", "server-auto", "http1"] }
tower-service = "0.3"
tower-http = { version = "0.5.2", features = ["trace"] }
silverpelt = { path = "../../core/rust.silverpelt" }

[dependencies.tokio]
version = "1"
features = ["sync", "macros", "rt-multi-thread"]

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "next"
features = ["model", "http", "cache", "rustls_backend", "unstable"]

[dependencies.botox]
git = "https://github.com/infinitybotlist/botox"
branch = "main"
