[package]
name = "splashcore_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = { git = "https://github.com/serenity-rs/poise", branch = "serenity-next" }
chrono = { version = "0.4", features = ["serde"]}
indexmap = { version = "2", features = ["serde"] }
futures-util = "0.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
dashmap = { version = "5", features = ["serde", "inline", "rayon"] }
once_cell = "1"
sqlx = { version = "0.7", features = [ "runtime-tokio-rustls", "postgres", "chrono", "uuid", "json"] }
rusty-s3 = "0.5"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "rustls-tls-native-roots"] }
log = "0.4"
async-trait = "0.1.80"

# Text normalization
unicode-normalization = { version = "0.1.23", default-features = false }
encoding = "0.2.33"
encoding_rs = "0.8.34"
html-escape = "0.2.13"
icu = "1.5.0"
oem_cp = { version = "2.0.0", features = ["alloc"] }
regex = "1"
fancy-regex = "0.12"
rustc-hash = "2"

[dependencies.tokio]
version = "1"
features = ["sync", "macros", "rt-multi-thread"]

[dependencies.botox]
git = "https://github.com/infinitybotlist/botox"
branch = "main"

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "next"
features = ["model", "http", "cache", "rustls_backend", "unstable"]

[dependencies.kittycat]
git = "https://github.com/infinitybotlist/kittycat"
branch = "main"