use async_trait::async_trait;
use std::sync::Arc;

pub type Error = Box<dyn std::error::Error + Send + Sync>; // This is constant and should be copy pasted

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "type")]
pub enum SettingsError {
    /// Operation not supported
    OperationNotSupported {
        operation: OperationType,
    },
    /// Generic error
    Generic {
        message: String,
        src: String,
        typ: String,
    },
    /// Schema type validation error
    SchemaTypeValidationError {
        column: String,
        expected_type: String,
        got_type: String,
    },
    /// Schema null value validation error
    SchemaNullValueValidationError {
        column: String,
    },
    /// Schema check validation error
    SchemaCheckValidationError {
        column: String,
        check: String,
        error: String,
        accepted_range: String,
    },
    /// Missing or invalid field
    MissingOrInvalidField {
        field: String,
        src: String,
    },
    RowExists {
        column_id: String,
        count: i64,
    },
    RowDoesNotExist {
        column_id: String,
    },
    MaximumCountReached {
        max: usize,
        current: usize,
    },
}

pub struct SettingsData {
    pub pool: sqlx::PgPool,
    pub reqwest: reqwest::Client,
    pub object_store: Arc<splashcore_rs::objectstore::ObjectStore>,
    pub cache_http: botox::cache::CacheHttpImpl,
    pub serenity_context: serenity::all::Context,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[allow(dead_code)]
#[serde(tag = "type")]
pub enum ColumnType {
    /// A single valued column (scalar)
    Scalar {
        #[serde(flatten)]
        /// The value type
        inner: InnerColumnType,
    },
    /// An array column
    Array {
        #[serde(flatten)]
        /// The inner type of the array
        inner: InnerColumnType,
    },
}

impl ColumnType {
    /// Returns whether the column type is an array
    #[allow(dead_code)]
    pub fn is_array(&self) -> bool {
        matches!(self, ColumnType::Array { .. })
    }

    /// Returns whether the column type is a scalar
    #[allow(dead_code)]
    pub fn is_scalar(&self) -> bool {
        matches!(self, ColumnType::Scalar { .. })
    }

    pub fn new_scalar(inner: InnerColumnType) -> Self {
        ColumnType::Scalar { inner }
    }

    pub fn new_array(inner: InnerColumnType) -> Self {
        ColumnType::Array { inner }
    }
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[allow(dead_code)]
#[serde(tag = "type")]
pub enum InnerColumnTypeStringKind {
    /// Normal string
    Normal,
    /// A token that is autogenerated if not provided by the user
    Token {
        /// The default length of the secret if not provided by the user
        default_length: usize,
    },
    /// A textarea
    Textarea { ctx: String },
    /// A reference to a template by name
    TemplateRef { kind: String, ctx: String },
    /// A kittycat permission
    KittycatPermission,
    /// User
    User,
    /// Role
    Role,
    /// Emoji
    Emoji,
    /// Message
    Message,
    /// Modifier
    Modifier,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[allow(dead_code)]
#[serde(tag = "type")]
pub enum InnerColumnType {
    Uuid {},
    String {
        min_length: Option<usize>,
        max_length: Option<usize>,
        allowed_values: Vec<String>, // If empty, all values are allowed
        kind: InnerColumnTypeStringKind,
    },
    Timestamp {},
    TimestampTz {},
    Interval {},
    Integer {},
    Float {},
    BitFlag {
        /// The bit flag values
        values: indexmap::IndexMap<String, i64>,
    },
    Boolean {},
    Json {
        max_bytes: Option<usize>,
    },
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "type")]
pub enum ColumnSuggestion {
    Static { suggestions: Vec<String> },
    None {},
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(tag = "type")]
pub struct Column {
    /// The ID of the column on the database
    pub id: String,

    /// The friendly name of the column
    pub name: String,

    /// The description of the column
    pub description: String,

    /// The type of the column
    pub column_type: ColumnType,

    /// Whether or not the column is nullable
    ///
    /// Note that the point where nullability is checked may vary but will occur after pre_checks are executed
    pub nullable: bool,

    /// Suggestions to display
    pub suggestions: ColumnSuggestion,

    /// A secret field that is not shown to the user
    pub secret: bool,

    /// For which operations should the field be ignored for (essentially, read only)
    ///
    /// Semantics are defined by the Executor
    pub ignored_for: Vec<OperationType>,
}

impl PartialEq for Column {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Hash, Eq, serde::Serialize, serde::Deserialize)]
#[allow(dead_code)]
pub enum OperationType {
    View,
    Save,
    Delete,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Setting {
    /// The ID of the option
    pub id: String,

    /// The name of the option
    pub name: String,

    /// The description of the option
    pub description: String,

    /// The primary key of the table. Should be present in ID
    pub primary_key: String,

    /// Title template, used for the title of the embed
    pub title_template: String,

    /// The columns for this option
    pub columns: Arc<Vec<Column>>,

    /// Operation specific data
    pub supported_operations: Vec<OperationType>,

    /// The underlying data store to use for fetch operations
    ///
    /// This can be useful in cases where postgres/etc. is not the main underlying storage (for example, seaweedfs etc.)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub executor: OptionSettingExecutor,
}

impl PartialEq for Setting {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

/// Wraps `v` in the currently used wrapper
///
/// Currently, this is an Arc for now
pub fn settings_wrap<T>(v: T) -> Arc<T> {
    Arc::new(v)
}

/// This is the context provided to all hooks (post-actions, validators, etc.)
#[allow(dead_code)]
pub struct HookContext<'a> {
    pub author: serenity::all::UserId,
    pub guild_id: serenity::all::GuildId,
    pub data: &'a SettingsData, // The data object
}

/// Settings must have an executor. Lua templates can also be used to provide the executor using events
#[async_trait]
pub trait SettingExecutor: Send + Sync {
    /// View the settings data
    ///
    /// __limit and __offset, if found, contains the limit/offset of the query
    ///
    /// All Executors should return an __count value containing the total count of the total number of entries
    async fn view<'a>(
        &self,
        context: HookContext<'a>,
        filters: indexmap::IndexMap<String, splashcore_rs::value::Value>,
    ) -> Result<Vec<crate::state::State>, Error>;

    /// Saves the setting
    async fn save<'a>(
        &self,
        context: HookContext<'a>,
        state: &'a mut super::state::State,
    ) -> Result<crate::state::State, Error>;

    /// Deletes the setting
    async fn delete<'a>(
        &self,
        context: HookContext<'a>,
        pkey: splashcore_rs::value::Value,
    ) -> Result<crate::state::State, Error>;
}

impl std::fmt::Debug for dyn SettingExecutor {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "SettingSaver")
    }
}

#[derive(Clone)]
pub struct OptionSettingExecutor(pub Option<Arc<dyn SettingExecutor>>);

impl std::ops::Deref for OptionSettingExecutor {
    type Target = Option<Arc<dyn SettingExecutor>>;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl serde::Serialize for OptionSettingExecutor {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        None::<Option<usize>>.serialize(serializer)
    }
}

impl<'de> serde::Deserialize<'de> for OptionSettingExecutor {
    fn deserialize<D>(_deserializer: D) -> Result<OptionSettingExecutor, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        Ok(OptionSettingExecutor(None))
    }
}

impl std::fmt::Debug for OptionSettingExecutor {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "OptionSettingExecutor")
    }
}
