[package]
name = "splashcore_text"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1"
unicode-normalization = { version = "0.1.23", default-features = false }
encoding_rs = "0.8.34"
html-escape = "0.2.13"
icu = "1.5.0"
oem_cp = { version = "2.0.0", features = ["alloc"] }
regex = "1"
fancy-regex = "0.12"
rustc-hash = "2"
