name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  build_and_test:
    name: Botv2
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    strategy:
      matrix:
        toolchain:
          - nightly # Only nightly is guaranteed to work so don't bother with anything else for now
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.toolchain }}
          workspaces: "botv2/botv2 -> target"
      - name: Install dependencies
        run: sudo apt install pkg-config openssl libssl-dev build-essential clangd clang libclang-14-dev lld mold 
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: make buildall
        env:
          CI_BUILD: true
      # The below doesn't work due to ci issues (sigh)
      # - run: cargo test --verbose
      #  env:
      #    CI_BUILD: true
